//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wistellar.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wistellar.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          __       __         __ __
        ///.--.--.--|__.-----|  |_.-----|  |  .---.-.----.
        ///|  |  |  |  |__ --|   _|  -__|  |  |  _  |   _|
        ///|________|__|_____|____|_____|__|__|___._|__|
        ///.
        /// </summary>
        internal static string AsciiBanner {
            get {
                return ResourceManager.GetString("AsciiBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Usage:
        ///  {0} --add-user --username &lt;username&gt; --password &lt;password&gt; [--role &lt;role&gt;]
        ///  {0} --delete-user --username &lt;username&gt;
        ///  {0} --update-user --username &lt;username&gt; [--password &lt;password&gt;] [--role &lt;role&gt;]
        ///
        ///Supported roles: member, moderator, contributor, admin
        ///If no role is specified, &apos;member&apos; is used as default.
        ///.
        /// </summary>
        internal static string CompleteUsage {
            get {
                return ResourceManager.GetString("CompleteUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: --password is required for --add-user.
        /// </summary>
        internal static string ErrorPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown command &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: User &apos;{0}&apos; already exists.
        /// </summary>
        internal static string ErrorUserAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: --username is required.
        /// </summary>
        internal static string ErrorUsernameRequired {
            get {
                return ResourceManager.GetString("ErrorUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: User &apos;{0}&apos; not found.
        /// </summary>
        internal static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; not found or could not be deleted..
        /// </summary>
        internal static string ErrorUserNotFoundOrCouldNotDelete {
            get {
                return ResourceManager.GetString("ErrorUserNotFoundOrCouldNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created user &apos;{0}&apos; with role &apos;{1}&apos;..
        /// </summary>
        internal static string SuccessUserCreated {
            get {
                return ResourceManager.GetString("SuccessUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted user &apos;{0}&apos;..
        /// </summary>
        internal static string SuccessUserDeleted {
            get {
                return ResourceManager.GetString("SuccessUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated user &apos;{0}&apos;..
        /// </summary>
        internal static string SuccessUserUpdated {
            get {
                return ResourceManager.GetString("SuccessUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Invalid role &apos;{0}&apos;. Using default role &apos;Member&apos;..
        /// </summary>
        internal static string WarningInvalidRole {
            get {
                return ResourceManager.GetString("WarningInvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Invalid role &apos;{0}&apos;. Skipping role update..
        /// </summary>
        internal static string WarningInvalidRoleUpdate {
            get {
                return ResourceManager.GetString("WarningInvalidRoleUpdate", resourceCulture);
            }
        }
    }
}
