// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wistellar.Core;

#nullable disable

namespace Wistellar.Core.Migrations
{
    [DbContext(typeof(WiGleBackupContext))]
    partial class WiGleBackupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Wistellar.Core.Entities.AndroidMetadatum", b =>
                {
                    b.Property<string>("Locale")
                        .HasColumnType("TEXT")
                        .HasColumnName("locale");

                    b.ToTable("android_metadata", (string)null);
                });

            modelBuilder.Entity("Wistellar.Core.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("_id");

                    b.Property<double>("Accuracy")
                        .HasColumnType("float")
                        .HasColumnName("accuracy");

                    b.Property<double>("Altitude")
                        .HasColumnType("double")
                        .HasColumnName("altitude");

                    b.Property<string>("Bssid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bssid");

                    b.Property<double>("Lat")
                        .HasColumnType("double")
                        .HasColumnName("lat");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<double>("Lon")
                        .HasColumnType("double")
                        .HasColumnName("lon");

                    b.Property<long>("Time")
                        .HasColumnType("long")
                        .HasColumnName("time");

                    b.Property<int>("Transaction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction");

                    b.Property<int>("User")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external");

                    b.HasKey("Id");

                    b.HasIndex("Bssid");

                    b.HasIndex("Time", "Bssid")
                        .IsUnique();

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("Wistellar.Core.Entities.MccMnc", b =>
                {
                    b.Property<int>("PLMN")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plmn");

                    b.Property<string>("Bands")
                        .HasColumnType("TEXT")
                        .HasColumnName("bands");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<string>("ISO")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iso");

                    b.Property<int>("MCC")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mcc");

                    b.Property<int>("MNC")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mnc");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT")
                        .HasColumnName("operator");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("TADIG")
                        .HasColumnType("TEXT")
                        .HasColumnName("tadig");

                    b.HasKey("PLMN");

                    b.HasIndex("MCC", "MNC")
                        .IsUnique();

                    b.ToTable("mccmnc");
                });

            modelBuilder.Entity("Wistellar.Core.Entities.Network", b =>
                {
                    b.Property<string>("BSSID")
                        .HasColumnType("TEXT")
                        .HasColumnName("bssid");

                    b.Property<double>("BestLatitude")
                        .HasColumnType("double")
                        .HasColumnName("bestlat");

                    b.Property<int>("BestLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bestlevel");

                    b.Property<double>("BestLongitude")
                        .HasColumnType("double")
                        .HasColumnName("bestlon");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities");

                    b.Property<long?>("Dwell")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dwell");

                    b.Property<int>("Frequency")
                        .HasColumnType("INT")
                        .HasColumnName("frequency");

                    b.Property<long>("LastSeen")
                        .HasColumnType("long")
                        .HasColumnName("lasttime");

                    b.Property<double>("Lastlatitude")
                        .HasColumnType("double")
                        .HasColumnName("lastlat");

                    b.Property<double>("Lastlongitude")
                        .HasColumnType("double")
                        .HasColumnName("lastlon");

                    b.Property<int?>("Observations")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observations");

                    b.Property<long?>("Range")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range");

                    b.Property<string>("SSID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ssid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("W")
                        .HasColumnName("type");

                    b.HasKey("BSSID");

                    b.HasIndex("BestLongitude", "BestLatitude", "LastSeen", "Type", "SSID");

                    b.ToTable("network", (string)null);
                });

            modelBuilder.Entity("Wistellar.Core.Entities.OUI", b =>
                {
                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("mac");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Base16")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base16");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("organisation");

                    b.HasKey("MacAddress");

                    b.ToTable("oui");
                });

            modelBuilder.Entity("Wistellar.Core.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("_id");

                    b.Property<double>("Accuracy")
                        .HasColumnType("float")
                        .HasColumnName("accuracy");

                    b.Property<double>("Altitude")
                        .HasColumnType("double")
                        .HasColumnName("altitude");

                    b.Property<int>("BtVisible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bt_visible");

                    b.Property<int>("CellVisible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cell_visible");

                    b.Property<double>("Lat")
                        .HasColumnType("double")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double")
                        .HasColumnName("lon");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<byte[]>("Time")
                        .IsRequired()
                        .HasColumnType("long")
                        .HasColumnName("time");

                    b.Property<int>("WifiVisible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wifi_visible");

                    b.HasKey("Id");

                    b.ToTable("route", (string)null);
                });

            modelBuilder.Entity("Wistellar.Core.Entities.WsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("secret");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("ws_users");
                });

            modelBuilder.Entity("Wistellar.Core.Models.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("REAL");

                    b.Property<double>("AltitudeMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MfgrId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RCOIs")
                        .HasColumnType("TEXT");

                    b.Property<int>("RSSI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SSID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("observation");
                });

            modelBuilder.Entity("Wistellar.Core.Entities.Location", b =>
                {
                    b.HasOne("Wistellar.Core.Entities.Network", "Network")
                        .WithMany()
                        .HasForeignKey("Bssid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });
#pragma warning restore 612, 618
        }
    }
}
